name: "sync fork"

on:
        push:
                branches:  
                          - 'main'

jobs:
        sync:
                runs-on: 'ubuntu-latest'

                steps:
                        - uses: srt32/git-actions@v0.0.3
                          with:
                                  args: "status"
                      
