name: "sync fork"

on:
        schedule:
                - cron: '* * * * *'

jobs:
        sync:
                runs-on: 'ubuntu-latest'

                steps:
                        - uses: tgymnich/fork-sync@v1.2
                          with:
                                  github_token: ${{ secrets.ACCESS_TOKEN }}
                                  owner: YadalleeBilaal
                                  base: main
                                  head: main
                                  auto_approve: true
